### ISSUE TITLE
read_cell_formula() is not working

### ISSUE THREAD

**Issue by taesikkim** [automagica/automagica#120]
When I try below read_cell_formula() example in Automagica Documentation Release 2(Apr 02, 2020).

>excel = Excel()
> excel.write_cell_formula(1, 1, '=1+1')
> excel.read_cell_formula(1, 1)
'=1+1'

error message is below :
  File "C:\automagica\utilities.py", line 17, in wrapper
    return func(*args, **kwargs)
TypeError: read_cell_formula() missing 1 required positional argument: 'formula'

**Comment by koenvaneijk** [comment]
This has been resolved in the `master` branch!
