### ISSUE TITLE
delete_column()  is not working

### ISSUE THREAD

**Issue by taesikkim** [automagica/automagica#121]
delete_column()  is not working

When I try below delete_column() example in Automagica Documentation Release 2(Apr 02, 2020).

> excel = Excel()
> excel.write_cell(1, 1, 'Filled')
> excel.write_cell(2, 2, 'Filled')
> excel.write_cell(3, 3, 'Filled')
> excel.delete_column('B')

Error message is below :

  File "C:\automagica\utilities.py", line 17, in wrapper
    return func(*args, **kwargs)
  File "C:\automagica\activities.py", line 5046, in delete_column
    column_range = str(column) + "1"
NameError: name 'column' is not defined

**Comment by koenvaneijk** [comment]
Could not replicate this issue unfortunately, the example mentioned in the docstring works on our side.
