### ISSUE TITLE
run_macro() is not working

### ISSUE THREAD

**Issue by taesikkim** [automagica/automagica#122]
run_macro() is not working

When I try below run_macro() example in Automagica Documentation Release 2(Apr 02, 2020).

> excel = Excel('excel_with_macro.xlsm')  # I changed 'excel_with_macro.xlsx' to 'excel_with_macro.xlsm' 
> excel.run_macro('Macro1')

But run_macro() is not working and shows error message.

**Comment by koenvaneijk** [comment]
Please provide more detailed error information. We could not replicate the issue on our side and the example runs fine.
