### ISSUE TITLE
Error with pip install automagica on Windows

### ISSUE THREAD

**Issue by Unhype** [automagica/automagica#123]
Trying to run `pip install https://github.com/OakwoodAI/automagica/tarball/master`

I'm using python 3.8.2 with pip 20.0.2 on Windows 10, up to date.

Some people suggested I install openssl 32bit and add envs but it didn't help.

this is the error:

`Microsoft Windows [Version 10.0.18363.778]
$ pip install https://github.com/OakwoodAI/automagica/tarball/master
Collecting https://github.com/OakwoodAI/automagica/tarball/master
  Using cached https://github.com/OakwoodAI/automagica/tarball/master
Requirement already satisfied: requests==2.22.0 in c:\python38\lib\site-packages (from Automagica==2.1.12) (2.22.0)
Requirement already satisfied: selenium==3.7.0 in c:\python38\lib\site-packages (from Automagica==2.1.12) (3.7.0)
Requirement already satisfied: pywinauto==0.6.5 in c:\python38\lib\site-packages (from Automagica==2.1.12) (0.6.5)
Requirement already satisfied: openpyxl==2.4.8 in c:\python38\lib\site-packages (from Automagica==2.1.12) (2.4.8)
Requirement already satisfied: python-docx==0.8.6 in c:\python38\lib\site-packages (from Automagica==2.1.12) (0.8.6)
Requirement already satisfied: PyPDF2==1.26.0 in c:\python38\lib\site-packages (from Automagica==2.1.12) (1.26.0)
Requirement already satisfied: faker==2.0.3 in c:\python38\lib\site-packages (from Automagica==2.1.12) (2.0.3)
Requirement already satisfied: psutil==5.6.6 in c:\python38\lib\site-packages (from Automagica==2.1.12) (5.6.6)
Requirement already satisfied: PySimpleGUI==4.15.1 in c:\python38\lib\site-packages (from Automagica==2.1.12) (4.15.1)
Requirement already satisfied: keyring==21.0.0 in c:\python38\lib\site-packages (from Automagica==2.1.12) (21.0.0)
Collecting cryptography==2.3.1
  Using cached cryptography-2.3.1.tar.gz (449 kB)
Collecting pyad==0.6.0
  Using cached pyad-0.6.0.tar.gz (23 kB)
Collecting jupyterlab==1.2.4
  Using cached jupyterlab-1.2.4-py2.py3-none-any.whl (6.4 MB)
Collecting py-trello==0.13.0
  Using cached py-trello-0.13.0.tar.gz (29 kB)
Collecting plyer==1.4.0
  Using cached plyer-1.4.0-py3-none-any.whl (131 kB)
Collecting Pillow==7.0.0
  Using cached Pillow-7.0.0-cp38-cp38-win_amd64.whl (2.0 MB)
Collecting pyperclip==1.7.0
  Using cached pyperclip-1.7.0.tar.gz (15 kB)
Collecting PyAutoGUI==0.9.48
  Using cached PyAutoGUI-0.9.48.tar.gz (57 kB)
Collecting pysnmp==4.4.12
  Using cached pysnmp-4.4.12-py2.py3-none-any.whl (296 kB)
Collecting pandas==1.0.0
  Using cached pandas-1.0.0-cp38-cp38-win_amd64.whl (9.1 MB)
Collecting mss==5.0.0
  Using cached mss-5.0.0-py2.py3-none-any.whl (32 kB)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\python38\lib\site-packages (from requests==2.22.0->Automagica==2.1.12) (1.25.8)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\python38\lib\site-packages (from requests==2.22.0->Automagica==2.1.12) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\python38\lib\site-packages (from requests==2.22.0->Automagica==2.1.12) (2020.4.5.1)
Requirement already satisfied: idna<2.9,>=2.5 in c:\python38\lib\site-packages (from requests==2.22.0->Automagica==2.1.12) (2.8)
Requirement already satisfied: six in c:\python38\lib\site-packages (from pywinauto==0.6.5->Automagica==2.1.12) (1.14.0)
Requirement already satisfied: comtypes in c:\python38\lib\site-packages (from pywinauto==0.6.5->Automagica==2.1.12) (1.1.7)
Requirement already satisfied: jdcal in c:\python38\lib\site-packages (from openpyxl==2.4.8->Automagica==2.1.12) (1.4.1)
Requirement already satisfied: et_xmlfile in c:\python38\lib\site-packages (from openpyxl==2.4.8->Automagica==2.1.12) (1.0.1)
Requirement already satisfied: lxml>=2.3.2 in c:\python38\lib\site-packages (from python-docx==0.8.6->Automagica==2.1.12) (4.5.0)
Requirement already satisfied: text-unidecode==1.3 in c:\python38\lib\site-packages (from faker==2.0.3->Automagica==2.1.12) (1.3)
Requirement already satisfied: python-dateutil>=2.4 in c:\python38\lib\site-packages (from faker==2.0.3->Automagica==2.1.12) (2.8.1)
Requirement already satisfied: pywin32-ctypes!=0.1.0,!=0.1.1; sys_platform == "win32" in c:\python38\lib\site-packages (from keyring==21.0.0->Automagica==2.1.12) (0.2.0)
Requirement already satisfied: asn1crypto>=0.21.0 in c:\python38\lib\site-packages (from cryptography==2.3.1->Automagica==2.1.12) (1.3.0)
Requirement already satisfied: cffi!=1.11.3,>=1.7 in c:\python38\lib\site-packages (from cryptography==2.3.1->Automagica==2.1.12) (1.14.0)
Requirement already satisfied: setuptools in c:\python38\lib\site-packages (from pyad==0.6.0->Automagica==2.1.12) (41.2.0)
Collecting future
  Using cached future-0.18.2.tar.gz (829 kB)
Collecting jupyterlab-server~=1.0.0
  Using cached jupyterlab_server-1.0.7-py3-none-any.whl (27 kB)
Collecting jinja2>=2.10
  Using cached Jinja2-2.11.2-py2.py3-none-any.whl (125 kB)
Collecting notebook>=4.3.1
  Using cached notebook-6.0.3-py3-none-any.whl (9.7 MB)
Collecting tornado!=6.0.0,!=6.0.1,!=6.0.2
  Using cached tornado-6.0.4-cp38-cp38-win_amd64.whl (417 kB)
Collecting requests-oauthlib>=0.4.1
  Using cached requests_oauthlib-1.3.0-py2.py3-none-any.whl (23 kB)
Collecting pytz
  Using cached pytz-2019.3-py2.py3-none-any.whl (509 kB)
Collecting pymsgbox
  Using cached PyMsgBox-1.0.7.tar.gz (18 kB)
Collecting PyTweening>=1.0.1
  Using cached PyTweening-1.0.3.zip (15 kB)
Collecting pyscreeze>=0.1.21
  Using cached PyScreeze-0.1.26.tar.gz (23 kB)
Collecting pygetwindow>=0.0.5
  Using cached PyGetWindow-0.0.8.tar.gz (9.6 kB)
Collecting mouseinfo
  Using cached MouseInfo-0.1.3.tar.gz (10 kB)
Collecting pycryptodomex
  Using cached pycryptodomex-3.9.7-cp38-cp38-win_amd64.whl (14.1 MB)
Collecting pysmi
  Using cached pysmi-0.3.4-py2.py3-none-any.whl (80 kB)
Collecting pyasn1>=0.2.3
  Using cached pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
Collecting numpy>=1.13.3
  Using cached numpy-1.18.2-cp38-cp38-win_amd64.whl (12.8 MB)
Requirement already satisfied: pycparser in c:\python38\lib\site-packages (from cffi!=1.11.3,>=1.7->cryptography==2.3.1->Automagica==2.1.12) (2.20)
Collecting json5
  Using cached json5-0.9.4-py2.py3-none-any.whl (17 kB)
Collecting jsonschema>=3.0.1
  Using cached jsonschema-3.2.0-py2.py3-none-any.whl (56 kB)
Collecting MarkupSafe>=0.23
  Using cached MarkupSafe-1.1.1-cp38-cp38-win_amd64.whl (16 kB)
Collecting jupyter-client>=5.3.4
  Using cached jupyter_client-6.1.3-py3-none-any.whl (106 kB)
Collecting terminado>=0.8.1
  Using cached terminado-0.8.3-py2.py3-none-any.whl (33 kB)
Collecting ipykernel
  Using cached ipykernel-5.2.1-py3-none-any.whl (118 kB)
Collecting traitlets>=4.2.1
  Using cached traitlets-4.3.3-py2.py3-none-any.whl (75 kB)
Collecting jupyter-core>=4.6.1
  Using cached jupyter_core-4.6.3-py2.py3-none-any.whl (83 kB)
Collecting pyzmq>=17
  Using cached pyzmq-19.0.0-cp38-cp38-win_amd64.whl (1.1 MB)
Collecting nbformat
  Using cached nbformat-5.0.5-py3-none-any.whl (170 kB)
Collecting Send2Trash
  Using cached Send2Trash-1.5.0-py3-none-any.whl (12 kB)
Collecting prometheus-client
  Using cached prometheus_client-0.7.1.tar.gz (38 kB)
Collecting ipython-genutils
  Using cached ipython_genutils-0.2.0-py2.py3-none-any.whl (26 kB)
Collecting nbconvert
  Using cached nbconvert-5.6.1-py2.py3-none-any.whl (455 kB)
Collecting oauthlib>=3.0.0
  Using cached oauthlib-3.1.0-py2.py3-none-any.whl (147 kB)
Collecting pyrect
  Using cached PyRect-0.1.4.tar.gz (15 kB)
Collecting ply
  Using cached ply-3.11-py2.py3-none-any.whl (49 kB)
Collecting attrs>=17.4.0
  Using cached attrs-19.3.0-py2.py3-none-any.whl (39 kB)
Collecting pyrsistent>=0.14.0
  Using cached pyrsistent-0.16.0.tar.gz (108 kB)
Collecting pywinpty>=0.5; os_name == "nt"
  Using cached pywinpty-0.5.7-cp38-cp38-win_amd64.whl (1.3 MB)
Collecting ipython>=5.0.0
  Using cached ipython-7.13.0-py3-none-any.whl (780 kB)
Collecting decorator
  Using cached decorator-4.4.2-py2.py3-none-any.whl (9.2 kB)
Requirement already satisfied: pywin32>=1.0; sys_platform == "win32" in c:\python38\lib\site-packages (from jupyter-core>=4.6.1->notebook>=4.3.1->jupyterlab==1.2.4->Automagica==2.1.12) (227)
Collecting pygments
  Using cached Pygments-2.6.1-py3-none-any.whl (914 kB)
Collecting bleach
  Using cached bleach-3.1.4-py2.py3-none-any.whl (151 kB)
Collecting testpath
  Using cached testpath-0.4.4-py2.py3-none-any.whl (163 kB)
Collecting mistune<2,>=0.8.1
  Using cached mistune-0.8.4-py2.py3-none-any.whl (16 kB)
Collecting defusedxml
  Using cached defusedxml-0.6.0-py2.py3-none-any.whl (23 kB)
Collecting pandocfilters>=1.4.1
  Using cached pandocfilters-1.4.2.tar.gz (14 kB)
Collecting entrypoints>=0.2.2
  Using cached entrypoints-0.3-py2.py3-none-any.whl (11 kB)
Collecting prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0
  Using cached prompt_toolkit-3.0.5-py3-none-any.whl (351 kB)
Collecting backcall
  Using cached backcall-0.1.0.tar.gz (9.7 kB)
Collecting pickleshare
  Using cached pickleshare-0.7.5-py2.py3-none-any.whl (6.9 kB)
Collecting jedi>=0.10
  Using cached jedi-0.17.0-py2.py3-none-any.whl (1.1 MB)
Collecting colorama; sys_platform == "win32"
  Using cached colorama-0.4.3-py2.py3-none-any.whl (15 kB)
Collecting webencodings
  Using cached webencodings-0.5.1-py2.py3-none-any.whl (11 kB)
Collecting wcwidth
  Using cached wcwidth-0.1.9-py2.py3-none-any.whl (19 kB)
Collecting parso>=0.7.0
  Using cached parso-0.7.0-py2.py3-none-any.whl (100 kB)
Installing collected packages: cryptography, future, pyad, json5, ipython-genutils, decorator, traitlets, jupyter-core, pyzmq, tornado, jupyter-client, pywinpty, terminado, pygments, wcwidth, prompt-toolkit, backcall, pickleshare, parso, jedi, colorama, ipython, ipykernel, MarkupSafe, jinja2, attrs, pyrsistent, jsonschema, nbformat, Send2Trash, prometheus-client, webencodings, bleach, testpath, mistune, defusedxml, pandocfilters, entrypoints, nbconvert, notebook, jupyterlab-server, jupyterlab, oauthlib, requests-oauthlib, pytz, py-trello, plyer, Pillow, pyperclip, pymsgbox, PyTweening, pyscreeze, pyrect, pygetwindow, mouseinfo, PyAutoGUI, pycryptodomex, ply, pysmi, pyasn1, pysnmp, numpy, pandas, mss, Automagica
  Attempting uninstall: cryptography
    Found existing installation: cryptography 2.9
    Uninstalling cryptography-2.9:
      Successfully uninstalled cryptography-2.9
    Running setup.py install for cryptography ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Sunrat\\AppData\\Local\\Temp\\pip-install-xj8vybiy\\cryptography\\setup.py'"'"'; __file__='"'"'C:\\Users\\Sunrat\\AppData\\Local\\Temp\\pip-install-xj8vybiy\\cryptography\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Sunrat\AppData\Local\Temp\pip-record-6mt8ilr0\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\python38\Include\cryptography'
         cwd: C:\Users\Sunrat\AppData\Local\Temp\pip-install-xj8vybiy\cryptography\
    Complete output (109 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.8
    creating build\lib.win-amd64-3.8\cryptography
    copying src\cryptography\exceptions.py -> build\lib.win-amd64-3.8\cryptography
    copying src\cryptography\fernet.py -> build\lib.win-amd64-3.8\cryptography
    copying src\cryptography\utils.py -> build\lib.win-amd64-3.8\cryptography
    copying src\cryptography\__about__.py -> build\lib.win-amd64-3.8\cryptography
    copying src\cryptography\__init__.py -> build\lib.win-amd64-3.8\cryptography
    creating build\lib.win-amd64-3.8\cryptography\hazmat
    copying src\cryptography\hazmat\__init__.py -> build\lib.win-amd64-3.8\cryptography\hazmat
    creating build\lib.win-amd64-3.8\cryptography\x509
    copying src\cryptography\x509\base.py -> build\lib.win-amd64-3.8\cryptography\x509
    copying src\cryptography\x509\certificate_transparency.py -> build\lib.win-amd64-3.8\cryptography\x509
    copying src\cryptography\x509\extensions.py -> build\lib.win-amd64-3.8\cryptography\x509
    copying src\cryptography\x509\general_name.py -> build\lib.win-amd64-3.8\cryptography\x509
    copying src\cryptography\x509\name.py -> build\lib.win-amd64-3.8\cryptography\x509
    copying src\cryptography\x509\oid.py -> build\lib.win-amd64-3.8\cryptography\x509
    copying src\cryptography\x509\__init__.py -> build\lib.win-amd64-3.8\cryptography\x509
    creating build\lib.win-amd64-3.8\cryptography\hazmat\backends
    copying src\cryptography\hazmat\backends\interfaces.py -> build\lib.win-amd64-3.8\cryptography\hazmat\backends
    copying src\cryptography\hazmat\backends\__init__.py -> build\lib.win-amd64-3.8\cryptography\hazmat\backends
    creating build\lib.win-amd64-3.8\cryptography\hazmat\bindings
    copying src\cryptography\hazmat\bindings\__init__.py -> build\lib.win-amd64-3.8\cryptography\hazmat\bindings
    creating build\lib.win-amd64-3.8\cryptography\hazmat\primitives
    copying src\cryptography\hazmat\primitives\cmac.py -> build\lib.win-amd64-3.8\cryptography\hazmat\primitives
    copying src\cryptography\hazmat\primitives\constant_time.py -> build\lib.win-amd64-3.8\cryptography\hazmat\primitives
    copying src\cryptography\hazmat\primitives\hashes.py -> build\lib.win-amd64-3.8\cryptography\hazmat\primitives
    copying src\cryptography\hazmat\primitives\hmac.py -> build\lib.win-amd64-3.8\cryptography\hazmat\primitives
    copying src\cryptography\hazmat\primitives\keywrap.py -> build\lib.win-amd64-3.8\cryptography\hazmat\primitives
    copying src\cryptography\hazmat\primitives\mac.py -> build\lib.win-amd64-3.8\cryptography\hazmat\primitives
    copying src\cryptography\hazmat\primitives\padding.py -> build\lib.win-amd64-3.8\cryptography\hazmat\primitives
    copying src\cryptography\hazmat\primitives\serialization.py -> build\lib.win-amd64-3.8\cryptography\hazmat\primitives
    copying src\cryptography\hazmat\primitives\__init__.py -> build\lib.win-amd64-3.8\cryptography\hazmat\primitives
    creating build\lib.win-amd64-3.8\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\aead.py -> build\lib.win-amd64-3.8\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\backend.py -> build\lib.win-amd64-3.8\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\ciphers.py -> build\lib.win-amd64-3.8\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\cmac.py -> build\lib.win-amd64-3.8\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\decode_asn1.py -> build\lib.win-amd64-3.8\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\dh.py -> build\lib.win-amd64-3.8\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\dsa.py -> build\lib.win-amd64-3.8\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\ec.py -> build\lib.win-amd64-3.8\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\encode_asn1.py -> build\lib.win-amd64-3.8\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\hashes.py -> build\lib.win-amd64-3.8\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\hmac.py -> build\lib.win-amd64-3.8\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\rsa.py -> build\lib.win-amd64-3.8\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\utils.py -> build\lib.win-amd64-3.8\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\x25519.py -> build\lib.win-amd64-3.8\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\x509.py -> build\lib.win-amd64-3.8\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\__init__.py -> build\lib.win-amd64-3.8\cryptography\hazmat\backends\openssl
    creating build\lib.win-amd64-3.8\cryptography\hazmat\bindings\openssl
    copying src\cryptography\hazmat\bindings\openssl\binding.py -> build\lib.win-amd64-3.8\cryptography\hazmat\bindings\openssl
    copying src\cryptography\hazmat\bindings\openssl\_conditional.py -> build\lib.win-amd64-3.8\cryptography\hazmat\bindings\openssl
    copying src\cryptography\hazmat\bindings\openssl\__init__.py -> build\lib.win-amd64-3.8\cryptography\hazmat\bindings\openssl
    creating build\lib.win-amd64-3.8\cryptography\hazmat\primitives\asymmetric
    copying src\cryptography\hazmat\primitives\asymmetric\dh.py -> build\lib.win-amd64-3.8\cryptography\hazmat\primitives\asymmetric
    copying src\cryptography\hazmat\primitives\asymmetric\dsa.py -> build\lib.win-amd64-3.8\cryptography\hazmat\primitives\asymmetric
    copying src\cryptography\hazmat\primitives\asymmetric\ec.py -> build\lib.win-amd64-3.8\cryptography\hazmat\primitives\asymmetric
    copying src\cryptography\hazmat\primitives\asymmetric\padding.py -> build\lib.win-amd64-3.8\cryptography\hazmat\primitives\asymmetric
    copying src\cryptography\hazmat\primitives\asymmetric\rsa.py -> build\lib.win-amd64-3.8\cryptography\hazmat\primitives\asymmetric
    copying src\cryptography\hazmat\primitives\asymmetric\utils.py -> build\lib.win-amd64-3.8\cryptography\hazmat\primitives\asymmetric
    copying src\cryptography\hazmat\primitives\asymmetric\x25519.py -> build\lib.win-amd64-3.8\cryptography\hazmat\primitives\asymmetric
    copying src\cryptography\hazmat\primitives\asymmetric\__init__.py -> build\lib.win-amd64-3.8\cryptography\hazmat\primitives\asymmetric
    creating build\lib.win-amd64-3.8\cryptography\hazmat\primitives\ciphers
    copying src\cryptography\hazmat\primitives\ciphers\aead.py -> build\lib.win-amd64-3.8\cryptography\hazmat\primitives\ciphers
    copying src\cryptography\hazmat\primitives\ciphers\algorithms.py -> build\lib.win-amd64-3.8\cryptography\hazmat\primitives\ciphers
    copying src\cryptography\hazmat\primitives\ciphers\base.py -> build\lib.win-amd64-3.8\cryptography\hazmat\primitives\ciphers
    copying src\cryptography\hazmat\primitives\ciphers\modes.py -> build\lib.win-amd64-3.8\cryptography\hazmat\primitives\ciphers
    copying src\cryptography\hazmat\primitives\ciphers\__init__.py -> build\lib.win-amd64-3.8\cryptography\hazmat\primitives\ciphers
    creating build\lib.win-amd64-3.8\cryptography\hazmat\primitives\kdf
    copying src\cryptography\hazmat\primitives\kdf\concatkdf.py -> build\lib.win-amd64-3.8\cryptography\hazmat\primitives\kdf
    copying src\cryptography\hazmat\primitives\kdf\hkdf.py -> build\lib.win-amd64-3.8\cryptography\hazmat\primitives\kdf
    copying src\cryptography\hazmat\primitives\kdf\kbkdf.py -> build\lib.win-amd64-3.8\cryptography\hazmat\primitives\kdf
    copying src\cryptography\hazmat\primitives\kdf\pbkdf2.py -> build\lib.win-amd64-3.8\cryptography\hazmat\primitives\kdf
    copying src\cryptography\hazmat\primitives\kdf\scrypt.py -> build\lib.win-amd64-3.8\cryptography\hazmat\primitives\kdf
    copying src\cryptography\hazmat\primitives\kdf\x963kdf.py -> build\lib.win-amd64-3.8\cryptography\hazmat\primitives\kdf
    copying src\cryptography\hazmat\primitives\kdf\__init__.py -> build\lib.win-amd64-3.8\cryptography\hazmat\primitives\kdf
    creating build\lib.win-amd64-3.8\cryptography\hazmat\primitives\twofactor
    copying src\cryptography\hazmat\primitives\twofactor\hotp.py -> build\lib.win-amd64-3.8\cryptography\hazmat\primitives\twofactor
    copying src\cryptography\hazmat\primitives\twofactor\totp.py -> build\lib.win-amd64-3.8\cryptography\hazmat\primitives\twofactor
    copying src\cryptography\hazmat\primitives\twofactor\utils.py -> build\lib.win-amd64-3.8\cryptography\hazmat\primitives\twofactor
    copying src\cryptography\hazmat\primitives\twofactor\__init__.py -> build\lib.win-amd64-3.8\cryptography\hazmat\primitives\twofactor
    running egg_info
    writing src\cryptography.egg-info\PKG-INFO
    writing dependency_links to src\cryptography.egg-info\dependency_links.txt
    writing requirements to src\cryptography.egg-info\requires.txt
    writing top-level names to src\cryptography.egg-info\top_level.txt
    reading manifest file 'src\cryptography.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    no previously-included directories found matching 'docs\_build'
    warning: no previously-included files matching '*' found under directory 'vectors'
    writing manifest file 'src\cryptography.egg-info\SOURCES.txt'
    running build_ext
    generating cffi module 'build\\temp.win-amd64-3.8\\Release\\_padding.c'
    creating build\temp.win-amd64-3.8
    creating build\temp.win-amd64-3.8\Release
    generating cffi module 'build\\temp.win-amd64-3.8\\Release\\_constant_time.c'
    generating cffi module 'build\\temp.win-amd64-3.8\\Release\\_openssl.c'
    building '_openssl' extension
    creating build\temp.win-amd64-3.8\Release\build
    creating build\temp.win-amd64-3.8\Release\build\temp.win-amd64-3.8
    creating build\temp.win-amd64-3.8\Release\build\temp.win-amd64-3.8\Release
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\python38\include -Ic:\python38\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /Tcbuild\temp.win-amd64-3.8\Release\_openssl.c /Fobuild\temp.win-amd64-3.8\Release\build\temp.win-amd64-3.8\Release\_openssl.obj
    _openssl.c
    build\temp.win-amd64-3.8\Release\_openssl.c(546): fatal error C1083: Cannot open include file: 'openssl/opensslv.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2
    ----------------------------------------
  Rolling back uninstall of cryptography
  Moving to c:\python38\lib\site-packages\cryptography-2.9.dist-info\
   from C:\Python38\Lib\site-packages\~ryptography-2.9.dist-info
  Moving to c:\python38\lib\site-packages\cryptography\
   from C:\Python38\Lib\site-packages\~ryptography
ERROR: Command errored out with exit status 1: 'c:\python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Sunrat\\AppData\\Local\\Temp\\pip-install-xj8vybiy\\cryptography\\setup.py'"'"'; __file__='"'"'C:\\Users\\Sunrat\\AppData\\Local\\Temp\\pip-install-xj8vybiy\\cryptography\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Sunrat\AppData\Local\Temp\pip-record-6mt8ilr0\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\python38\Include\cryptography' Check the logs for full command output.
`

**Comment by tvturnhout** [comment]
Hi Unhype,

Automagica currently officially supports Python 3.7.X , could you perhaps try again with this version of Python?

**Comment by Unhype** [comment]
It worked when I downgraded to Python 3.7.7

thanks!
