### ISSUE TITLE
is it possible to get attributes of an element with Automagica?

### ISSUE THREAD

**Issue by Unhype** [automagica/automagica#124]
in Selenium I could just add `.getAttribute("href")` after an element to get the value. Is something like this possible in Automagica? If not, is there a workaround?

I was trying: `browser.by_xpaths('//a/@href')`
but it throws: `invalid selector: The result of the xpath expression "//a/@href" is: [object Attr]. It should be an element.`

**Comment by koenvaneijk** [comment]
The method is `.get_attribute('href')`.

Please refer to the [Selenium Python binding documentation](https://selenium-python.readthedocs.io/). It's pretty good!
