### ISSUE TITLE
automagica installation problem (under both: pip & PyCharm)

### ISSUE THREAD

**Issue by Dirk-2020** [automagica/automagica#127]
Maybe I am just missing an aspect here, but cannot resolve and no Google help found:
Installation stops for both pip and PyCharm with issue regarding 'openssl/opensslv.h' when it tries to install cryptography-2.9.2 (although I have that installed already).
Any ideas?

**Comment by koenvaneijk** [comment]
What version of Python are you using?

**Comment by Dirk-2020** [comment]
3.8.3, but also tried 3.7

**Comment by koenvaneijk** [comment]
What OS are you using?

**Comment by Dirk-2020** [comment]
Win10

**Comment by Dirk-2020** [comment]
Currently try to re-install whole chain, starting with Visual Studio Community 2019...

**Comment by koenvaneijk** [comment]
Have you tried the installer from the Portal?

If you're interested, I can invitr you to the closed beta pf Automagica
Flow. Send me an e-mail at koen@automagica.com and I'll share you the link.
It's a one-click installer for Windows.

**Comment by Dirk-2020** [comment]
Yep, the installer from the Portal. I'll send you an email. Thx a lot.
