### ISSUE TITLE
SAP GUI Error in code

### ISSUE THREAD

**Issue by roloow** [automagica/automagica#129]
I was playing arround with automagica, an found that in `activities.py` in **line 9394**, there is an error where it is use 

`self.process = Popen(self.sap_logon_exe_path)`

and it should be

`self.process = Popen(sap_logon_exe_path)`

**Comment by koenvaneijk** [comment]
hi @roloow,

Thanks for your addition!

This would indeed fail if a `sap_logon_exe_path` is provided as keyword argument.

We'll include this in our next release!

Kind regards,
Koen
Co-founder
Automagica.com

**Comment by koenvaneijk** [comment]
This has been resolved in the latest release.
