### ISSUE TITLE
SAP GUI Children access get error with saplogo.HLP

### ISSUE THREAD

**Issue by roloow** [automagica/automagica#130]
Another issue I encounter while playing arround with automagica, was that I could not access to de session or by that matter I could not retrieve info by ussing accessing into children process.

So, I opened the sap client by calling

```
from subprocess import Popen
process = Popen('path/to/saplogon.exe')
sapgui = win32com.client.GetObject("SAPGUI")
engine = sapgui.GetScriptingEngine
```

Till here, no problem, however, when trying to access the connection

```
engine.Children(0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "B:pathto\env\lib\site-packages\win32com\client\dynamic.py", line 197, in __call__
    return self._get_good_object_(self._oleobj_.Invoke(*allArgs),self._olerepr_.defaultDispatchName,None)
pywintypes.com_error: (-2147352567, 'Exception occurred.', (614, 'saplogon', 'The enumerator of the collection cannot find en element with the specified index.', 'pathto\\SAPgui\\saplogon.HLP', 393215, 0), None)
```
it crushes, actually `engine.Children.Count` returns `0`. In order to bypass this I used

```
con = engine.OpenConnection('nameofconection')
```
This works fine, and opens the login window of sap. After this point, nothing works. neither `engine.FindById("ses[0]")` nor `con.Children(0)`.

All with the same problem, searching for saplogon.HLP and that file does not actually exists.

**Comment by koenvaneijk** [comment]
Hi @roloow 

Are you getting this error with the SAPGUI-class from Automagica?

Are you trying this with an enterprise system or with a sandboxed SAP? 

We've never seen this issue in the past but of course happy to help you. Perhaps send me an e-mail at koen@automagica.com so I can follow up in-person with you.

Kind regards,
Koen
Co-founder
Automagica.com

**Comment by roloow** [comment]
I tried using the SAPGUI class from automagica but it failed so I tried step by step what the class was called. Im using an enterprise sap client

**Comment by koenvaneijk** [comment]
Closing this issue as this is not an issue for Automagica.
