### ISSUE TITLE
Automagica Flow If-Else Condition

### ISSUE THREAD

**Issue by kohlu** [automagica/automagica#132]
Hello, I'm having an issue using an "If Else" node in Automagica Flow 3.0.5 on Windows 10 x64. 

The flowchart looks like the image below.

![Screenshot_2020-08-10_16-11-47](https://user-images.githubusercontent.com/1444576/89832110-95fe5480-db24-11ea-8c07-8fa607b93a7f.png)

In the "Random boolean" node, I set the "Return variable" field to a variable called "cond". 

![Capture1](https://user-images.githubusercontent.com/1444576/89832519-14f38d00-db25-11ea-94e4-f6ce00913247.PNG)

In the "If Else" node, I set the "Condition" field to the same variable "cond".

![Capture](https://user-images.githubusercontent.com/1444576/89832372-d3fb7880-db24-11ea-96da-6e9ccbc722cf.PNG)

This seems to work fine. Running the flow several times will print either "True" or "False" half the time. However, after I save this flow and reopen the .json file, the "Condition" field in the "If Else" node becomes blank. In the .json file itself, the the condition field is then automatically set to null somehow. Is this a known issue or am I setting the condition field incorrectly?

I've pasted the .json file of the example. Notice the condition field is set to "cond" like I intended. This gets overwritten with null once I reopen the file, and view the "If Else" node properties.

```
{
    "nodes": [
        {
            "uid": "6QO5",
            "x": 100,
            "y": 100,
            "type": "StartNode",
            "next_node": "6wpc",
            "label": ""
        },
        {
            "uid": "slyW",
            "x": 450,
            "y": 100,
            "type": "IfElseNode",
            "next_node": "lOSB",
            "else_node": "Lg7P",
            "label": "",
            "condition": "cond"
        },
        {
            "uid": "6wpc",
            "x": 275,
            "y": 100,
            "type": "ActivityNode",
            "next_node": "slyW",
            "label": "",
            "activity": "automagica.activities.generate_random_boolean",
            "args": {},
            "class": null,
            "return_": "cond",
            "on_exception_node": null
        },
        {
            "uid": "lOSB",
            "x": 625,
            "y": 100,
            "type": "PythonCodeNode",
            "next_node": null,
            "code": "print(\"True\")\n\n\n",
            "on_exception_node": null,
            "label": "Print True"
        },
        {
            "uid": "Lg7P",
            "x": 450,
            "y": 225,
            "type": "PythonCodeNode",
            "next_node": null,
            "code": "print(\"False\")\n\n",
            "on_exception_node": null,
            "label": "Print False"
        }
    ],
    "name": "Unnamed Flow"
}
```

Thanks!

**Comment by koenvaneijk** [comment]
Hi @kohlu 

Thanks for raising this issue.

I pushed a fix to master which resolves this. 

Line 79 needs to be `condition=d["condition"]`, instead of `d["condition"]`.

This fix will be included in 3.0.8.

Kind regards,
Koen
Automagica
