### ISSUE TITLE
Add capability to read e-mails from Outlook sub-folders

### ISSUE THREAD

**Issue by juanvasquezreyes** [automagica/automagica#133]
I have a question, I was able to retrieve the emails in my inbox, but how can I retrieve emails that are in subfolder in archive folder?

For example in a nested archive directory? 
[Example](https://cms-assets.tutsplus.com/uploads/users/988/posts/30938/image/outlook-lost-emails%20(1b).jpg)

**Comment by koenvaneijk** [comment]
@juanvasquezreyes thank you for your suggestion. I have marked the issue as an enhancement.

As a current workaround, we suggest you make the folder a top-level folder in your Outlook and use a naming convention, for example "Directory/Folder1" and "Directory/Folder2".
