### ISSUE TITLE
Open Chrome Browser not working in Docker

### ISSUE THREAD

**Issue by juanvasquezreyes** [automagica/automagica#134]
I'm testing Docker image and when I open automagica flow and try to start chrome it is not opening and is not working

Do you know what libraries are missing? I already tried installing chrome by myself and also install chromedriver-py and pip3 install chromedriver-py

**Comment by UmutAlihan** [comment]
As I could discover you need to place crhomedriver ona specific directory if you are on linux:

For Windows: 
D:\Dev\automagica\venv\Lib\site-packages\automagica\bin\win32

For Linux:
You need to mkdir a new dir called Linux64 
mkdir -p /path/to/python/module/site-packages/automagica/bin/Linux64/  (path can be wrong, but you get the point)
Place your chromedriver file here

**Comment by koenvaneijk** [comment]
Closing as this issue is resolved.
