### ISSUE TITLE
drag_mouse_to_coordinates activity: TypeError: drag() missing 2 required positional arguments: 'end_x' and 'end_y'

### ISSUE THREAD

**Issue by UmutAlihan** [automagica/automagica#137]
I try to use drag_mouse_to_coordinates activity as mentioned in the Documentation:

```python
automagica.activities.drag_mouse_to_coordinates(x=None, y=None, delay=1)
automagica.activities.drag_mouse_to_coordinates(x=500, y=500)
```

However I get the error below:
```python
TypeError: drag() missing 2 required positional arguments: 'end_x' and 'end_y'
```

I try to give those arguments "end_x", "end_y" it still fails.

**Comment by kathawala** [comment]
@UmutAlihan looks like a bug in the `drag_mouse_to_coordinates` function

These lines

```python
if x and y:
    from mouse import drag
    drag(x, y, absolute=False)
```

Don't match the API for `drag` from the `mouse` library. The function signature for `drag` is

```python
mouse.drag(start_x, start_y, end_x, end_y, absolute=True, duration=0)
```

So the lines in automagica should look something like

```python
if x and y:
    from mouse import drag
    xy = mouse.get_position()
    drag(xy[0], xy[1], x, y, absolute=False)
```

**Comment by UmutAlihan** [comment]
Thank you @kathawala for the solution. It works flawlessly!!
