### ISSUE TITLE
All the magic has gone on 13.10.2020

### ISSUE THREAD

**Issue by itsergiu** [automagica/automagica#146]
All the libraries disappeared from GitHub. 
```pip install automagica``` is still working, but you will stop it in 3 months, right?
There is no open source RPA starting with 13.10.2020, right?
Automagica has been built on top of other open source Python libraries and nothing left in one day.
It feels like a scam, what does community think?

**Comment by kathawala** [comment]
It's probably time for a community supported fork.

I have a fork which allows OCR separately from the Portal. Didn't maintain it because I expected it to be merged in eventually.

If somebody wants to make a list of features which require the Portal we can fork from the last version of the code which was available under AGPL and try to replace those features with local alternatives

**Comment by tvturnhout** [comment]
Hi @itsergiu and @kathawala 

Having worked on the open source project for three years we’ve taken the decision to integrate it with Netcall’s Liberty platform. As I’m sure you can appreciate we were developing it fulltime and the costs of running the central AI-driven Wand and OCR features were increasing as usage grew. It became unsustainable for us.

The acquisition gives us the ability to realise the dream for Automagica, we’ll have the time needed to develop the software full-time and additional resources to support us. We're already working on huge improvements to the Attended RPA functionality, exciting! Netcall will also be able to offer the kind of enterprise support and SLA’s we’d never be able to.

I hope you understand our decision and I’d like to thank the community for the messages of support we’ve had this week.

**Comment by kathawala** [comment]
@tvturnhout Yeah, count me in as one who supports you and is happy you turned your own software into something successful. That's the dream for so many of us. I definitely am happy to see you made it a reality!

**Comment by itsergiu** [comment]
@kathawala Imagine scikit-learn.org overnight deletes all libraries to turn the project into something commercial successful. How many contributors will be willing to contribute for other Python libraries? How many developers would like invest time to use a open source library and post issues if the project can disappear any moment?

**Comment by kathawala** [comment]
@itsergiu 

I am willing to continue maintaining the open source version by forking the project with a different name. But I would need some help. Would you be willing to help me out?

No one is obligated to write free code for you. The creators of this project were generous enough to make the code open for us. Now they are moving on to closed source. We can still maintain it in our free time. Want to do that with me?

**Comment by itsergiu** [comment]
@kathawala I saw discontinued projects, but this time I saw how a project disappeared in one day and this was my misunderstanding.  I agree with you "The creators of this project were generous enough to make the code open for us". The project has 2.4k stars which means community is interested in this project including myself. I can give a hand.

**Comment by aikarjal** [comment]
@kathawala @itsergiu If you're interested in an open-source fork of Automagica, [Robocorp](https://robocorp.com/) is able to support that effort. Keeping the project alive and independent is in our interests as well. We are building open-source RPA tools that are based on Python and Robot Framework, and we have an orchestration platform that can be used to run Automagica bots as well. Reach out to me on [LinkedIn](https://www.linkedin.com/in/aikarjal/) or email (antti at robocorp.com).

We are also working to publish our python robot packaging format (robot.yaml) as open-source... That will allow you to build easily portable python bots. Current docs can be found [here](https://robocorp.com/docs/product-manuals/robocorp-cli/robocorp-cli-overview) but the project hasn't been published yet. You can still download the CLI tool and try it out already.
