### ISSUE TITLE
TripleClick funcionality

### ISSUE THREAD

**Issue by carlosmonari** [automagica/automagica#47]
hi everybody,

it's possible implement this funcionality in automagica ?

------------------------------------------------------------------
in file activities.py

def TripleClickOnPosition(x=None, y=None):
    '''
    Triple clicks on a pixel position on the visible screen determined by x and y coördinates.
    '''
    return pyautogui.tripleClick(x, y)

------------------------------------------------------------------

I put this funcion in my fork and i use this when i need to capture all phrase text in webpage ...
it's very usefull.

Thanks for advance.

**Comment by koenvaneijk** [comment]
Hi @carlosmonari 

Thank you so much for your contribution.

We will shortly include this in our building block functions.

In the meanwhile, a pull request is greatly appreciated.

Kind regards,
Koen

**Comment by koenvaneijk** [comment]
This can be emulated in the following way:
```python
for _ in range(2):
    click(x=100, y=100)
```
Closing this issue for now.
