### ISSUE TITLE
It is closing browser when used version selenium-3.7.0, automagica and Windows10

### ISSUE THREAD

**Issue by carlosmonari** [automagica/automagica#48]
Hi guys,

I found a bug when used automagica with in selenium-3.7.0 in windows 10.

The browser closed when we use a function Type:

for exemple:

def OpenSite(login, password):
    browser = ChromeBrowser()
    browser.get('https://site.com/blahblahblah....')
    PressKey('enter')
    Wait(seconds=5)
    #positioning in login field to enter
    ClickOnPosition(x=780, y=295)
    Wait(seconds=1)

    Type(text=login, interval_seconds=0)  <- here is the problem

    ClickOnPosition(x=548, y=480)
    Wait(seconds=1)
    Type(text=password, interval_seconds=0)

    # confirm button 
    ClickOnPosition(x=448, y=529) 
    Wait(seconds=5)

in moment to execute "Type" the browser is do closed.

i resolved my problem doing upgrade to selenium-3.141.0 

Is it possible to change the setup.py file to the majored version of selenium?

Thanks!

**Comment by koenvaneijk** [comment]
Thanks @carlosmonari for your sharing your findings. 

This is at the top of our priority list.

Kind regards,
Koen

**Comment by kool601** [comment]
I'm having this issue on macOS Catalina, and even though I upgraded my Selenium to the latest version, it still closes after it's done typing whatever I put in.

**Comment by koenvaneijk** [comment]
@kool601 you're always welcome to submit a pull request.

This issue can be closed as this has been resolved.
