### ISSUE TITLE
How can we check if a window exists?

### ISSUE THREAD

**Issue by UmutAlihan** [automagica/automagica#74]
For example if we get a prompt pop up window such as "Are you really sure to save it?" or "do you want to overwrite existing file?"

I would like to check whether such window popped up or not  and take action accordingly

**Comment by tvturnhout** [comment]
If you know the title of your pop up, you could perhaps try to loop over all the (sub)windows of an application.

E.g. by using pywinauto

`from pywinauto import Application`
`app = Application(backend="win32").connect(title=TITLE OF YOUR APPLICATION')`

`for wnd in app.windows():`
    `if wnd.window_text() =='POPUP TITLE' and wnd.is_visible():`  
        ` TAKE ACTION`

**Comment by UmutAlihan** [comment]
thank you very much!

**Comment by Praseena1610** [comment]
TypeError: item 2 in _argtypes_ passes a union by value, which is unsupported.

I get this error if i import pywinauto. Can you please help this

**Comment by tvturnhout** [comment]
We made an additional activity to find a window based on title, documentation can be found here: https://automagica.readthedocs.io/activities.html#automagica.activities.find_window_title .

Does that solve your problem?

**Comment by Praseena1610** [comment]
Yes thank you!
