### ISSUE TITLE
CoInitialize issue when using win32com features

### ISSUE THREAD

**Issue by Ronald-TR** [automagica/automagica#78]
When i use `ConvertWordToPDF` and some SAP module automation, i faced the following error: "CoInitialize has not been called".

This issue is eventual, and i think that this is more about win32com module (in microsoft api part) than automagica itself.

Otherwise, the solution for me it's to calling before ConvertWordToPDF (for example), the CoInitialize syncronization:
```python
import pythoncom
try:
    pythoncom.CoInitializeEx(pythoncom.COINIT_MULTITHREADED)
except pythoncom.error as E:
    # Some other thread beat us to initialization - not a real
    # problem.
    # your treatment here
    raise E
```

I think that this can helps someone else and maybe this can be inserted in automagica in somewere to avoid this CoInitialize issue.

**Comment by koenvaneijk** [comment]
For future reference, this is also noted in the `pywinauto` docs:
https://github.com/OakwoodAI/Automagica/blob/master/examples/rpa_challenge_com_solution.ipynb
