### ISSUE TITLE
 why WaitForImage() is not  working 

### ISSUE THREAD

**Issue by vishal96-kadam** [automagica/automagica#83]

**Comment by koenvaneijk** [comment]
Could you please provide some more information? What image are you trying to find? Do you receive any errors?

**Comment by vishal96-kadam** [comment]
i want to use wait function dynamically
in which no need to define wait
the process will wait until the response from URLin which i don't want to
use chrome driver

regards
vishal kadam

**Comment by koenvaneijk** [comment]
Please try the new Automagica Vision activities we just released.

Hope this helps!

Kind regards,
Koen
Automagica.com
